apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo
  namespace: argocd
  
spec:
  project: demo
  source:
    repoURL: https://github.com/dayo777
    path: kargo
  destination:
    name: kargo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true